charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/service.yaml
I've added the `.enabled` suffix to both the conditions for the healthcheck.
So that it can get boolean value from the respective key fields.
=> Fixed condition issue for disabling the health check.

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/values.yaml
=> feat/healthcheck update added type tcpSocket

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/cronjob.yaml, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/templates/worker.yaml, charts/polymorphic-app/values.yaml
Closes #42 
- Added support for `successfulJobHistoryLimit` and `failedJobHistoryLimit` for `CronJob`.
- Added support for `dnsConfig` for `Deployment`.
=> feat: new features for polymorphic-app chart #42

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/values.yaml
=> fixed the healthcheck probes taking twice

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/values.yaml
- Added `ingressClassName` field to service.
=> feat: added ingress class to service

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/values.yaml
=> Fix/polymorphic app/added ingress class

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/cronjob.yaml, charts/polymorphic-app/values.yaml
=> fix the cronjob to take 0 as historylimit

.github/workflows/lint-test.yaml, .github/workflows/release.yaml, charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/cronjob.yaml, charts/polymorphic-app/templates/job.yaml, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/templates/worker.yaml, charts/polymorphic-app/values.yaml
Closes #56 
Add flag for remove prefix in every kubernetes resources
=> Add flag for remove prefix in every kubernetes resources #56

charts/frigate/Chart.yaml, charts/frigate/templates/Statefulset.yaml, charts/frigate/templates/config-pvc.yaml, charts/frigate/values.yaml
-  Feat: added pvc for the config required by frigate version 0.13.0.
-  Fix: fixed the volumeclaims in the sts with values are not being picked-up by values.
=> Feat: Update the frigate version to 0.13.0 and added pvc for config and fixed vct in sts.

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/_helpers.tpl, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/templates/worker.yaml, charts/polymorphic-app/values.yaml
- updated hpa apiversion support for polymorphic chart
=> updated hpa apiversion for worker and service

index.yaml
=> Aded supabase

.github/workflows/lint-test.yaml, .github/workflows/release.yaml, charts/proxysql/.helmignore, charts/proxysql/Chart.yaml, charts/proxysql/ci/override-values.yaml, charts/proxysql/templates/_helpers.tpl, charts/proxysql/templates/deployment.yaml, charts/proxysql/templates/pdb.yaml, charts/proxysql/templates/service.yaml, charts/proxysql/values.yaml
=> feat: Added proxysql helm chart

index.yaml
=> feat: add apache nifi helm chart by changing indexfile

index.yaml
Added new version of nifi chart with new nifi.properties
=> Feat/add index nifi chart 2.0.1

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/worker.yaml, charts/polymorphic-app/values.yaml
Added annotations in worker.
Use case:
Need annotations to restart worker everytime there is change in configMaps, Secrets via Stakater.
=> feat: add annotations support in worker

charts/nifi-registry/.helmignore, charts/nifi-registry/Chart.yaml, charts/nifi-registry/templates/NOTES.txt, charts/nifi-registry/templates/_helpers.tpl, charts/nifi-registry/templates/cert-manager.yaml, charts/nifi-registry/templates/configmap.yaml, charts/nifi-registry/templates/ingress.yaml, charts/nifi-registry/templates/service.yaml, charts/nifi-registry/templates/serviceaccount.yaml, charts/nifi-registry/templates/statefulset.yaml, charts/nifi-registry/values.yaml
=> Added nifi-registry chart

charts/kore-board/.helmignore, charts/kore-board/Chart.yaml, charts/kore-board/templates/cluster-role.yaml, charts/kore-board/templates/configmap.yaml, charts/kore-board/templates/pvc-metrics-scraper.yaml, charts/kore-board/templates/role.yaml, charts/kore-board/templates/workload-backend.yaml, charts/kore-board/templates/workload-frontend.yaml, charts/kore-board/templates/workload-metrics-scraper.yaml, charts/kore-board/templates/workload-terminal.yaml, charts/kore-board/values.yaml
- added new chart `kore-board`.
- Dashboard UI for Kubernetes.
=> feat: added new chart `kore-dashboard` dashboard ui for k8s.

charts/kore-board/Chart.yaml, charts/kore-board/templates/workload-backend.yaml
- fix the issue of multiple resource block in the backend in kore-board.
=> fix: backend in kore-board multiple resources block.

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/values.yaml
Closes  https://github.com/Improwised/releases/issues/1268
- Here I want podAnnotation in application which is deployed using polymorphic-chart
=> podAnnotations added in serviceTemplate

charts/apexkube/.helmignore, charts/apexkube/Chart.yaml, charts/apexkube/templates/_helpers.tpl, charts/apexkube/templates/clusterrole.yaml, charts/apexkube/templates/clusterrolebinding.yaml, charts/apexkube/templates/crds/organization.platformengineers.io_accounts.yaml, charts/apexkube/templates/crds/organization.platformengineers.io_users.yaml, charts/apexkube/templates/service.yaml, charts/apexkube/templates/serviceaccount.yaml, charts/apexkube/values.yaml
Created helmchart for apexkube with crds and roles 
Closes: #103
=> feat: added helmchart for apexkube with crds #103

charts/apexkube/Chart.yaml, charts/apexkube/templates/clusterrole.yaml, charts/apexkube/templates/service.yaml
- changed CR and deployment in apexkube
=> fix: changed crb and deployment in apexkube chart

.github/workflows/release.yaml, charts/polymorphic-app/Chart.yaml
- update Ci for Sign The charts
=> feat: update ci for sign the chart

.github/workflows/release.yaml
=> fix: Fixes Export GPG key Step

charts/polymorphic-app/Chart.yaml, charts/polymorphic-app/templates/service.yaml, charts/polymorphic-app/templates/worker.yaml, charts/polymorphic-app/values.schema.json
- Fix the issue in min_replica to 0 issue in polymorphic-app chart
=> fix: min_replica to 0 issue in polymorphic-app chart
